### ISSUE TITLE
Running too long will turn negative

### ISSUE THREAD

**Issue by legoxi** [ashbz/BruteBTC#1]
<img width="168" alt="6bd86cd6512169bcc0e9f43034fafb2" src="https://user-images.githubusercontent.com/112492771/195466673-cda8bea7-dec9-4c65-81dd-bcbdb8ecd415.png">

**Comment by legoxi** [comment]
Is it a display problem? Will it affect the continued operation?

**Comment by ashbz** [comment]
It will not affect operation, it's just integer overflow. You can keep it running 24/7 365 with no issues.
